import { getConfigValue } from '@dropins/tools/lib/aem/configs.js';
import { getUserTokenCookie } from './initializers/index.js';
import { getConsent } from './commerce.js';

async function initAnalytics() {
  try {
    // Load Commerce events SDK and collector
    // only if "analytics" has been added to the config.
    const analyticsConfig = getConfigValue('analytics');

    if (analyticsConfig && getConsent('commerce-collection')) {
      window.adobeDataLayer.push(
        {
          storefrontInstanceContext: {
            baseCurrencyCode: analyticsConfig['base-currency-code'],
            environment: analyticsConfig.environment,
            environmentId: analyticsConfig['environment-id'],
            storeCode: analyticsConfig['store-code'],
            storefrontTemplate: 'EDS',
            storeId: parseInt(analyticsConfig['store-id'], 10),
            storeName: analyticsConfig['store-name'],
            storeUrl: analyticsConfig['store-url'],
            storeViewCode: analyticsConfig['store-view-code'],
            storeViewCurrencyCode: analyticsConfig['base-currency-code'],
            storeViewId: parseInt(analyticsConfig['store-view-id'], 10),
            storeViewName: analyticsConfig['store-view-name'],
            websiteCode: analyticsConfig['website-code'],
            websiteId: parseInt(analyticsConfig['website-id'], 10),
            websiteName: analyticsConfig['website-name'],
            viewId: analyticsConfig['view-id'], // applicable for ACO storefronts
            // setting locale if defined, applicable for ACO storefronts
            ...(analyticsConfig.locale && { locale: analyticsConfig.locale }),
          },
        },
        {
          eventForwardingContext: {
            commerce: true,
            aep: !!(analyticsConfig['aep-ims-org-id'] && analyticsConfig['aep-datastream-id']),
          },
        },
        {
          shopperContext: {
            shopperId: getUserTokenCookie() ? 'logged-in' : 'guest',
          },
        },
        {
          aepContext: {
            imsOrgId: analyticsConfig['aep-ims-org-id'],
            datastreamId: analyticsConfig['aep-datastream-id'],
          },
        },
      );

      // Load events SDK and collector
      import('./commerce-events-sdk.js');
      import('./commerce-events-collector.js');
    }
  } catch (error) {
    console.warn('Error initializing analytics', error);
  }
}

if (document.prerendering) {
  document.addEventListener('prerenderingchange', initAnalytics, { once: true });
} else {
  initAnalytics();
}

// add delayed functionality here

// Demo Inspector (auto-generated by Demo Builder)
try {
  const { initInspector } = await import('./demo-inspector-init.js');
  initInspector();
} catch { /* Inspector not available */ }

// === Smart 404 PDP rebuild (Demo Builder) ===
// Auto-publishes the per-product page when a visitor hits a cold PDP
// URL. Matches /products/{urlKey}/{sku}; otherwise no-op. Replaces the
// storefront's default "Page Not Found" body with a "Loading product…"
// state the moment the gate passes so the user gets immediate feedback
// during the ~1-2 second cold-publish window.
(function smart404PdpRebuild() {
  if (!window.isErrorPage) return;
  const RETRY_FLAG = 'pdpRetry';
  const m = window.location.pathname.match(/^\/products\/([^/]+)\/([^/]+)$/);
  if (!m) return;
  if (new URLSearchParams(window.location.search).has(RETRY_FLAG)) return;
  const [, urlKey, sku] = m;
  const lc = `/products/${urlKey.toLowerCase()}/${sku.toLowerCase()}`;
  // Reveal the body now that we're ready to show our own loading state.
  // The eager script in 404.html injected a "visibility: hidden" style
  // to suppress the default 404 chrome during the cold-path window;
  // removing it now lets our loading state render.
  const hideStyle = document.getElementById('smart-404-cold-hide');
  if (hideStyle) hideStyle.remove();
  // Replace the 404 body with a loading state. Element-level inline
  // style attributes are governed by style-src 'unsafe-inline' (not
  // the nonce or strict-dynamic), and storefront CSPs we have
  // inspected allow this by default. Reusing the storefront <main>
  // keeps header and footer chrome intact. Uses the storefront design
  // tokens with hardcoded fallbacks so the loading state still
  // renders cleanly when a storefront does not define them. Clear
  // main's class so the default 404 chrome (e.g. main.error's own
  // flex layout) does not compete with our flex centering and push
  // the message off-center.
  const mainEl = document.querySelector('main');
  // Loading state: a centered spinner with "Loading product…" caption.
  // Uses storefront design tokens for color/typography with hardcoded
  // fallbacks. Spinner is a CSS-only rotating ring (no images, no
  // assets to load) so it renders instantly the moment we paint.
  const WRAP = 'display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:50vh;padding:var(--spacing-large,40px) var(--spacing-medium,20px);gap:var(--spacing-medium,20px);';
  const SPIN = 'width:48px;height:48px;border:4px solid var(--color-neutral-200,#f0f0f0);border-top-color:var(--color-brand-500,#454545);border-radius:50%;animation:smart404Spin 0.8s linear infinite;';
  const TEXT = 'font:var(--type-body-1-default-font,1.25rem/1.5 sans-serif);color:var(--color-brand-500,#454545);';
  const ANIM = '<style>@keyframes smart404Spin{to{transform:rotate(360deg)}}</style>';
  const LOADING_HTML = `<div style="${WRAP}"><div style="${SPIN}"></div><div style="${TEXT}">Loading product…</div></div>${ANIM}`;
  if (mainEl) {
    mainEl.className = '';
    mainEl.innerHTML = LOADING_HTML;
  }
  (async () => {
    if (lc !== window.location.pathname) {
      try {
        const head = await fetch(lc, { method: 'HEAD' });
        if (head.ok) {
          window.location.replace(lc);
          return;
        }
      } catch (_) { /* fall through to trigger */ }
    }
    const triggerUrl = `https://285361-249darkllama-stage.adobeioruntime.net/api/v1/web/accs-discovery/prepublish-pdp?org=kmanns&site=justrite&path=${encodeURIComponent(lc)}`;
    // One retry on 5xx with 1s backoff. Covers I/O Runtime cold start
    // + transient runtime failures without piling up retries that
    // would make a real outage take twice as long to surface.
    async function tryTrigger() {
      try {
        return await fetch(triggerUrl, { method: 'POST' });
      } catch (_) {
        return null;
      }
    }
    let r = await tryTrigger();
    if (!r || (r.status >= 500 && r.status < 600)) {
      await new Promise((res) => { setTimeout(res, 1000); });
      r = await tryTrigger();
    }
    if (r && r.ok) {
      const sep = lc.includes('?') ? '&' : '?';
      window.location.replace(`${lc}${sep}${RETRY_FLAG}=1`);
      return;
    }
    // Action failed after retry — the SKU has no publishable PDP
    // (deleted, renamed, or never existed in Commerce). The honest UX
    // is the storefront's native /404, not a custom in-place message
    // that implies the product page exists. A full redirect makes the
    // URL bar, history, and bookmarks all reflect reality. /404 does not
    // match the PDP pattern, so this never loops.
    window.location.replace('/404');
  })();
}());
// === end Smart 404 PDP rebuild ===
